---
- hosts: gruppo3
  become: yes
  remote_user:  user
  become_user: root
  become_method: sudo
  gather_facts: no
  tasks:
    - name: Remove "apache2" package
      apt:
        name: apache2
        state: absent
